name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Setup SSH
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USER }}
          KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >> ~/.ssh/config << EOF
          Host vps
            HostName $HOST
            User $USERNAME
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
            ServerAliveInterval 60
            ServerAliveCountMax 10
          EOF

      - name: Deploy to VPS
        run: |
          ssh vps '
            set -e
            export PATH=$PATH:/home/$USER/.nvm/versions/node/v18/bin
            cd ~/projects/cicd-pipeline
            git fetch origin main
            git reset --hard origin/main
            npm ci
            npm run build
            if pm2 list | grep -q "next-app"; then
              pm2 reload next-app
            else
              pm2 start npm --name "next-app" -- start
            fi
          '

      - name: Cleanup SSH
        if: always()
        run: rm -rf ~/.ssh/deploy_key ~/.ssh/config